### ISSUE TITLE
addTrack

### ISSUE THREAD

**Issue by mp1pro** [baconfatlabs/jammming#1]
AddTrack can be simplified like so
```

 addTrack(track) {
    let tracks = this.state.playlistTracks;
    if (!tracks.includes(track)) {
      tracks.push(track);
      this.setState({playlistTracks: tracks});
    }
}
```

**Comment by baconfatlabs** [comment]
Thanks.  I have incorporated your suggestion as listed.  Totally forgot about .includes().  I'm not sure the training focused on it at length so it wasn't fresh in my mind.
