### ISSUE TITLE
savePlayList

### ISSUE THREAD

**Issue by mp1pro** [baconfatlabs/jammming#2]
Instead of saving the Playlist to spotify then updating it in setState. We should do both actions in one go using the .then() method.

```
  savePlaylist() {
    const trackUris = this.state.playlistTracks.map(track => track.uri);
    Spotify.savePlaylist(this.state.playlistName, trackUris).then(() => {
      this.setState({
        playlistName: 'New Playlist',
        playlistTracks: []
      });
    });
  }
```

**Comment by baconfatlabs** [comment]
Hi, I originally tried your suggestion with a chained .then(), however, it generates a runtime error: TypeError: Cannot read property 'then' of undefined. 

Just for transparency, here's the exact codeblock for savePlaylist() as I just tested it:

`  savePlaylist(){
    const trackURIs = this.state.playlistTracks.map( track => track.uri );

    Spotify.savePlaylist(this.state.playlistName, trackURIs).then(() => {
      this.setState({
        playlistName: 'New Playlist',
        playlistTracks: []
      });
    });

//    this.setState({
//      playlistName: 'New Playlist',
//      searchResults: [],
//      playlistTracks: []
//    });

  }`

If you can figure out why this is occurring, I'd be happy to leave it in the chain, but the syntax in your code block currently breaks my application.

**Comment by mp1pro** [comment]
For more info, refer to react advisors at codecademy.com

Marvin Parke
Web Developer
cel phone: 3058963657
Github: https://github.com/mp1pro
Linkedin: https://www.linkedin.com/in/marvinparke
