### ISSUE TITLE
Beware of spelling errors that may break your state

### ISSUE THREAD

**Issue by farishkash** [baconfatlabs/jammming#4]
https://github.com/baconfatlabs/jammming/blob/master/src/Components/App/App.js#L32

      this.setState({playylistTracks: tracks});

**Comment by baconfatlabs** [comment]
Thanks.  Odd.  That didn't actually break functionality for some reason, but I fixed the typo.  I wonder if I just fat fingered something after I published it to surge.  Oh well.  It is what it is!
