### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [baconfatlabs/jammming#6]
Overall met expectations.

Great project, like the you may like feature that you did.  First time I have seen that done with this project, Kudos.

Basically beware of spelling errors, that was the only one I noticed but that is breaking the state of your project.

If you like as an additional challenge take a look at this and see what other experimentations you can do.  This is an autocomplete search concept I wrote up for another React Learner.

https://codepen.io/Farish/pen/QOWRpB

**Comment by farishkash** [comment]
Well I made a mistake and was suppose to review the feature request document but after looking over it and this project they were both great.

**Comment by baconfatlabs** [comment]
Either way, thanks for looking at them both.  I'll take a look at your mod if I have some time before the API cohort I'm signing up for.
